    // ===== NAV =====
    function toggleNav() {
      document.getElementById('mob-nav-btn').classList.toggle('open');
      document.getElementById('mob-nav-menu').classList.toggle('open');
    }
    function closeNav() {
      document.getElementById('mob-nav-btn').classList.remove('open');
      document.getElementById('mob-nav-menu').classList.remove('open');
    }

    // ===== I18N =====
    const T = {
      ru: {
        cover_tag: 'Брендбук · 2026',
        cover_title: 'Руководство по фирменному стилю',
        cover_year: 'Стокгольм · Стамбул · 2026',
        mission_quote: 'Стать надежным мостом на пути к <span style="color: #9830D5;">осознанности</span>, <span style="color: #9830D5;">трансформации</span> и возвращению к своей подлинной природе.',
        mission_sub: 'Моя миссия',
        strategy_label: 'Моя стратегия',
        strategy_text: 'Я не останавливаюсь на решении сиюминутных проблем. Пока человек идёт по пути я <span style="color: #9830D5;">рядом до результата</span>.',
        s01_tag: '01 — Название',
        s01_title: 'Что означает FinGuide Expert',
        fin_origin: 'от англ. Finance',
        fin_desc: 'Финансы — ядро экспертизы. Всё, что касается денег, налогов, учёта и финансовой независимости.',
        guide_origin: 'от англ. Guide — проводник',
        guide_desc: 'Не просто консультант, а проводник. Тот, кто ведёт туда, куда сам клиент не смог бы дойти в одиночку.',
        expert_origin: 'от лат. Expertus — опытный',
        expert_desc: 'Более 20 лет практики, международные сертификаты, подтверждённый профессионализм.',
        mc1_title: 'Выбор названия',
        mc1_text: 'Название выбрано осознанно: финансовая грамотность — главная тема работы. Трансформационная игра по финграмотности, коучинг, налоговый консалтинг — всё это объединяется в одном слове <strong>FinGuide</strong>.',
        mc2_title: 'Позиционирование',
        mc2_text: 'FinGuide Expert — это не бухгалтерская фирма и не просто курсы. Это личный финансовый навигатор для тех, кто хочет управлять деньгами осознанно и грамотно.',
        mc3_title: 'Запоминаемость',
        mc3_text: 'Короткое, международное, легко произносится на казахском, русском и английском языках. Работает как в цифровом пространстве, так и офлайн.',
        mc4_title: 'Масштабируемость',
        mc4_text: 'Название не ограничивает географию и не привязано к конкретному городу. Растёт вместе с автором — от Актобе до любой точки Казахстана и СНГ.',
        s02_tag: '01 — Логотип',
        s02_title: 'Логотип и его символика',
        le1_title: 'Татьяна',
        le1_text: 'это имя эксперта',
        le2_title: 'Онтюрклер',
        le2_text: 'это фамилия эксперта',
        logo_versions: 'Версии логотипа',
        lv1_label: '01 — Основная',
        lv1_text: 'На светлом и нейтральном фоне. Документы, сайт, презентации, соцсети.',
        lv2_label: '02 — На тёмном фоне',
        lv2_text: 'Логотип на чёрном. Баннеры, тёмные обложки, рекламные материалы.',
        lv3_label: '03 — Монохром',
        lv3_text: 'Чёрный монохром. Печать на светлых носителях, штампы, вышивка, гравировка.',
        s021_tag: '02 — Иконка',
        s021_title: 'Графический символ',
        icon_desc: 'Иконка — самостоятельный графический символ бренда. Золотой глобус с горизонтальными линиями на прозрачном фоне. Используется там, где полное название нецелесообразно или не помещается.',
        icon_d1_title: 'Цифровые носители',
        icon_d1_text: 'Favicon сайта, аватар в Instagram / Telegram / WhatsApp, иконка мобильного приложения, аватар почты.',
        icon_d2_title: 'Печать и упаковка',
        icon_d2_text: 'Штамп, наклейка, тиснение на обложке, водяной знак в документах, элемент оформления сертификатов.',
        icon_d3_title: 'Декоративный элемент',
        icon_d3_text: 'Паттерн на фоне презентаций, декор угла страницы, разделитель между блоками.',
        icon_d4_title: 'Требования',
        icon_d4_text: 'Минимальный размер — 32×32 px. Не деформировать, не перекрашивать. Охранная зона — 20% от диаметра.',
        dl_tag: 'Исходные файлы',
        dl_title: 'Логотип в формате PSD (Adobe Photoshop)',
        dl_desc: 'Векторные слои, все версии логотипа, редактируемый исходник',
        dl_btn: 'Скачать PSD',
        s04_tag: '02 — Типографика',
        s04_title: 'Фирменный шрифт',
        font_sub: 'Основной шрифт (Google Fonts · Бесплатный · Кириллица · Латиница · Турецкий)',
        font_sub_compacta: 'Имя Tatyana. Используется в логотипе.',
        font_sub_bella: 'Фамилия Ontyurkler. Используется в логотипе.',
        fw1: 'Подзаголовки, вспомогательный текст',
        fw2: 'Основной текст, описания',
        fw3: 'Акценты, подписи',
        fw4: 'Заголовки, логотип',
        typo_rules_title: 'Правила использования',
        tr1_title: '✓ Основной шрифт — Montserrat',
        tr1_text: 'В логотипе слово Tatyana — это Compacta BT Cyr, а Ontyurkler — Bella Script Cyr. Но так как в текстах они нечитаемы, на сайте, в буклетах и брендбуке используется исключительно Montserrat.',
        tr2_title: '✓ Кириллица, латиница, турецкий',
        tr2_text: 'Montserrat поддерживает все необходимые письменности. Специфические турецкие буквы отображаются корректно.',
        tr3_title: '✗ Не использовать другие шрифты',
        tr3_text: 'Запрещено использовать Times New Roman, Arial, Comic Sans и любые другие шрифты в официальных материалах бренда.',
        tr4_title: '✗ Не искажать',
        tr4_text: 'Не растягивать, не сжимать, не наклонять текст вручную. Используйте только встроенные начертания Montserrat.',
        s03_tag: '03 — Цвета',
        s03_title: 'Фирменная палитра',
        c1_role: 'Основной',
        c2_role: 'Акцентный / Текст',
        c3_role: 'Фоновый',
        c4_role: 'Переходный градиент',
        c4_role: 'Фоновый',
        cm1_title: 'Фиолетовый — осознанность и глубина',
        cm1_text: 'Глубокий фиолетовый цвет символизирует трансформацию, духовность и выход на новый уровень. Это цвет осознанности и внутреннего роста.',
        cm2_title: 'Чёрный — строгость и профессионализм',
        cm2_text: 'Чёрный цвет создает сильный контраст, придает бренду премиальность, элегантность и стабильность.',
        cm3_title: 'Градиент — динамика и переход',
        cm3_text: 'Плавный переход от насыщенного фиолетового к глубокому чёрному символизирует процесс трансформации и перетекание энергии.',
        cm4_title: 'Белый — чистота и свобода',
        cm4_text: 'Белый цвет выступает как пространство для дыхания. Он дает легкость, подчеркивает открытость и готовность к новому началу.',
        s06_tag: '04 — Эксперт',
        s06_title: 'Лицо бренда',
        expert_name: 'Онтюрклер<br/>Татьяна',
        expert_role: 'Трансперсональный психолог · Нумеролог · Автор выездных программ',
        expert_bio_1: 'В своей работе я помогаю людям глубже понимать свою природу, видеть смысл происходящих событий и находить внутреннюю опору в периоды перемен. Мой подход объединяет психологию, трансперсональные методы самопознания, нумерологию и практики осознанности.',
        expert_bio_2: 'Помимо индивидуальной работы, я создаю выездные программы и ретриты, где участники могут восстановить внутренний ресурс и встретиться с собой настоящими. Для меня работа с человеком — это сопровождение на пути осознанности и раскрытия своей подлинной природы.',
        s07_tag: '06 — Применение',
        s07_title: 'Логотип в жизни',
        moc1: 'Блокнот с гравировкой',
        moc2: 'Визитная карточка',
        moc3: 'Неоновая вывеска',
        moc4: 'Мерч · Футболка',
        moc5: 'Фирменная кружка',
        s08_tag: '07 — Запрещённые использования',
        s08_title: 'Как нельзя использовать логотип',
        s08_desc: 'Логотип — лицо бренда. Любое искажение разрушает узнаваемость и профессиональный образ. Ниже примеры того, что категорически запрещено.',
        d1_title: '✗ Растягивать',
        d1_text: 'Запрещено изменять пропорции логотипа. Используйте только масштабирование с сохранением сторон.',
        d2_title: '✗ Перекрашивать',
        d2_text: 'Запрещено изменять фирменные цвета логотипа. Используйте только утверждённую палитру.',
        d3_title: '✗ Наклонять',
        d3_text: 'Логотип всегда размещается строго горизонтально. Наклон и вращение запрещены.',
        d4_title: '✗ Пёстрый фон',
        d4_text: 'Запрещено размещать логотип на ярких, пёстрых или слишком контрастных фонах.',
        d5_title: '✗ Добавлять тени',
        d5_text: 'Запрещено добавлять тени, свечение и любые эффекты к логотипу.',
        d6_overlay: 'ДРУГОЙ ТЕКСТ',
        d6_title: '✗ Добавлять элементы',
        d6_text: 'Запрещено накладывать поверх логотипа текст, рамки или посторонние графические элементы.',
        ct_phone: 'Телефон',
        ct_address: 'Адрес',
        ct_city: 'г. Актобе,<br/>Республика Казахстан',
        page_indicator: 'Стокгольм · Стамбул · 2026',
        nav_audience: 'Аудитория',
        nav_name: 'Название',
        nav_logo: 'Логотип',
        nav_icon: 'Иконка',
        nav_typo: 'Типографика',
        nav_colors: 'Цвета',
        nav_expert: 'Лицо бренда',
        nav_mockups: 'Применение',
        nav_dont: 'Запрещено',
        nav_digital: 'Домен',
        nav_contacts: 'Контакты',
        s00_tag: '05 — Целевая аудитория',
        s00_title: 'Кому помогает FinGuide Expert',
        s00_desc: 'Бренд создан для трёх чётко определённых аудиторий — каждая со своей задачей и точкой входа.',
        aud1_num: '01', aud2_num: '02', aud3_num: '03',
        aud_goal: 'Запрос',
        aud1_title: 'Начинающие и работающие бухгалтеры',
        aud1_text: 'Девушки, обучающиеся на бухгалтера или уже работающие в профессии. Хотят повысить квалификацию, стать увереннее в налогах и стать настоящим экспертом — не просто исполнителем.',
        aud1_goal: 'Рост экспертности · Профессиональное признание',
        aud2_title: 'Состоявшиеся бизнесмены',
        aud2_text: 'Владельцы бизнеса, у которых уже есть дело, но финансы ведутся хаотично. Хотят навести порядок в учёте, оптимизировать налоги и получить чёткое понимание финансового состояния компании.',
        aud2_goal: 'Порядок в финансах · Налоговая оптимизация',
        aud3_title: 'Молодые предприниматели и стартаперы',
        aud3_text: 'Начинающие предприниматели, которые только открывают своё дело. Хотят с самого старта выстроить финансовую грамотность: ИП, налоги, учёт — чтобы бизнес рос без болезненных ошибок.',
        aud3_goal: 'Финграмотность с нуля · Правильный старт',
        s09_tag: '08 — Цифровое присутствие',
        s09_title: 'Рекомендуемый домен',
        s09_desc: 'Единый адрес бренда в интернете. Используйте его во всех материалах — онлайн и офлайн.',
        s09_rec: 'Рекомендуется к регистрации',
        s09_avail: 'Домен в зоне RU · Короткий и запоминающийся адрес',
        s09_r1_tag: '✓ Сайт и email',
        s09_r1_text: 'Основной сайт размещать на <strong>ontat.ru</strong>. Email использовать в формате <strong>tatyana@ontat.ru</strong> — выглядит профессионально и укрепляет доверие.',
        s09_r2_tag: '✓ Соцсети',
        s09_r2_text: 'Указывать домен <strong>ontat.ru</strong> в описании профилей Instagram, Telegram, WhatsApp. Единая точка входа для аудитории из любого канала.',
        s09_r3_tag: '✓ Печатные материалы',
        s09_r3_text: 'Визитные карточки, флаеры, сертификаты, баннеры — везде указывать <strong>ontat.ru</strong>. Без лишних символов: никаких http://, www. или слеша в конце.',
        s09_r4_tag: '✓ Единообразие',
        s09_r4_text: 'Один домен — один адрес во всех каналах. Это формирует узнаваемость бренда и упрощает навигацию для клиентов. Не использовать сторонние сервисы (Taplink, Linktree) как основной адрес.',
        s09_note: 'Домен ontat.ru рекомендуется к регистрации как можно скорее — до начала активного продвижения бренда. Это застрахует от ситуации, когда желаемый адрес окажется занят.',
      },
      en: {
        cover_tag: 'Brandbook · 2026',
        cover_title: 'Brand Identity Guidelines',
        cover_year: 'Stockholm · Istanbul · 2026',
        mission_quote: 'To become a reliable bridge on the path to <span style="color: #9830D5;">awareness</span>, <span style="color: #9830D5;">transformation</span>, and returning to your true nature.',
        mission_sub: 'My Mission',
        strategy_label: 'My Strategy',
        strategy_text: 'I do not stop at solving momentary problems. As long as a person is on the path, I am <span style="color: #9830D5;">nearby until the result</span>.',
        s01_tag: '01 — Name',
        s01_title: 'What it means',
        fin_origin: 'from Finance',
        fin_desc: 'Finance is the core expertise. Everything about money, taxes, accounting, and financial independence.',
        guide_origin: 'from Guide',
        guide_desc: 'Not just a consultant, but a guide. Someone who leads where the client could not reach alone.',
        expert_origin: 'from Expertus — experienced',
        expert_desc: 'Over 20 years of practice, international certificates, proven professionalism.',
        mc1_title: 'Name Selection',
        mc1_text: 'The name was chosen consciously: financial literacy is the main theme of the work.',
        mc2_title: 'Positioning',
        mc2_text: 'It is a personal financial navigator for those who want to manage money consciously and competently.',
        mc3_title: 'Memorability',
        mc3_text: 'Short, international, easy to pronounce in Kazakh, Russian and English. Works both digitally and offline.',
        mc4_title: 'Scalability',
        mc4_text: 'The name does not limit geography and is not tied to a specific city.',
        s02_tag: '01 — Logo',
        s02_title: 'Logo and its symbolism',
        le1_title: 'Tatyana',
        le1_text: 'is the expert\'s first name',
        le2_title: 'Ontyurkler',
        le2_text: 'is the expert\'s last name',
        logo_versions: 'Logo versions',
        lv1_label: '01 — Main',
        lv1_text: 'On light and neutral backgrounds. Documents, website, presentations, social networks.',
        lv2_label: '02 — On dark background',
        lv2_text: 'Logo on black. Banners, dark covers, promotional materials.',
        lv3_label: '03 — Monochrome',
        lv3_text: 'Black monochrome. Printing on light media, stamps, embroidery, engraving.',
        s021_tag: '02 — Icon',
        s021_title: 'Graphic symbol',
        icon_desc: 'The icon is an independent graphic symbol of the brand. Used where the full name is inappropriate or does not fit.',
        icon_d1_title: 'Digital media',
        icon_d1_text: 'Website Favicon, Instagram / Telegram / WhatsApp avatar, mobile app icon, email avatar.',
        icon_d2_title: 'Printing and packaging',
        icon_d2_text: 'Stamp, sticker, embossing on the cover, watermark in documents, certificate design element.',
        icon_d3_title: 'Decorative element',
        icon_d3_text: 'Pattern on the background of presentations, corner decoration of the page, separator between blocks.',
        icon_d4_title: 'Requirements',
        icon_d4_text: 'Minimum size — 32×32 px. Do not deform, do not repaint. Protection zone — 20% of the diameter.',
        dl_tag: 'Source files',
        dl_title: 'Logo in PSD format (Adobe Photoshop)',
        dl_desc: 'Vector layers, all versions of the logo, editable source',
        dl_btn: 'Download PSD',
        s04_tag: '02 — Typography',
        s04_title: 'Corporate font',
        font_sub: 'Main font (Google Fonts · Free · Cyrillic · Latin · Turkish)',
        font_sub_compacta: 'Name Tatyana. Used in the logo.',
        font_sub_bella: 'Surname Ontyurkler. Used in the logo.',
        fw1: 'Subheadings, supporting text',
        fw2: 'Body text, descriptions',
        fw3: 'Accents, captions',
        fw4: 'Headings, logo',
        typo_rules_title: 'Usage rules',
        tr1_title: '✓ Main font — Montserrat',
        tr1_text: 'In the logo, the word Tatyana is Compacta BT Cyr, and Ontyurkler is Bella Script Cyr. But since they are unreadable in texts, only Montserrat is used on the website, in booklets and in the brandbook.',
        tr2_title: '✓ Cyrillic, Latin, Turkish',
        tr2_text: 'Montserrat supports all necessary scripts. Specific Turkish letters are displayed correctly.',
        tr3_title: '✗ Do not use other fonts',
        tr3_text: 'It is forbidden to use Times New Roman, Arial, Comic Sans and any other fonts in the official materials of the brand.',
        tr4_title: '✗ Do not distort',
        tr4_text: 'Do not stretch, compress, or tilt text manually. Use only built-in Montserrat styles.',
        s03_tag: '03 — Colors',
        s03_title: 'Corporate palette',
        c1_role: 'Main',
        c2_role: 'Accent / Text',
        c3_role: 'Background',
        c4_role: 'Transition gradient',
        cm1_title: 'Purple — awareness and depth',
        cm1_text: 'Deep purple symbolizes transformation, spirituality and reaching a new level. It is the color of awareness and inner growth.',
        cm2_title: 'Black — strictness and professionalism',
        cm2_text: 'Black creates a strong contrast, gives the brand a premium feel, elegance and stability.',
        cm3_title: 'Gradient — dynamics and transition',
        cm3_text: 'A smooth transition from rich purple to deep black symbolizes the process of transformation and the flow of energy.',
        cm4_title: 'White — purity and freedom',
        cm4_text: 'White acts as breathing space. It gives lightness, emphasizes openness and readiness for a new beginning.',
        s06_tag: '04 — Expert',
        s06_title: 'Face of the brand',
        expert_name: 'Ontyurkler<br/>Tatyana',
        expert_role: 'Transpersonal psychologist · Numerologist · Author of retreat programs',
        expert_bio_1: 'In my work, I help people deeply understand their nature, see the meaning of ongoing events, and find inner support during times of change. My approach combines psychology, transpersonal self-discovery methods, numerology, and mindfulness practices.',
        expert_bio_2: 'In addition to individual work, I create retreat programs where participants can restore their inner resources and meet their true selves. For me, working with a person is accompanying them on the path of awareness and revealing their true nature.',
        s07_tag: '06 — Application',
        s07_title: 'Logo in real life',
        moc1: 'Engraved notebook',
        moc2: 'Business card',
        moc3: 'Neon sign',
        moc4: 'Merch · T-shirt',
        moc5: 'Branded mug',
        s08_tag: '07 — Prohibited uses',
        s08_title: 'How not to use the logo',
        s08_desc: 'The logo is the face of the brand. Any distortion destroys recognition and a professional image. Below are examples of what is strictly prohibited.',
        d1_title: '✗ Stretch',
        d1_text: 'It is forbidden to change the proportions of the logo. Use only scaling while maintaining the aspect ratio.',
        d2_title: '✗ Repaint',
        d2_text: 'It is forbidden to change the corporate colors of the logo. Use only the approved palette.',
        d3_title: '✗ Tilt',
        d3_text: 'The logo is always placed strictly horizontally. Tilting and rotation are prohibited.',
        d4_title: '✗ Colorful background',
        d4_text: 'It is forbidden to place the logo on bright, colorful or too contrasting backgrounds.',
        d5_title: '✗ Add shadows',
        d5_text: 'It is forbidden to add shadows, glows and any effects to the logo.',
        d6_overlay: 'OTHER TEXT',
        d6_title: '✗ Add elements',
        d6_text: 'It is forbidden to overlay text, frames or extraneous graphic elements on top of the logo.',
        ct_phone: 'Phone',
        ct_address: 'Address',
        ct_city: 'Aktobe,<br/>Republic of Kazakhstan',
        page_indicator: 'Stockholm · Istanbul · 2026',
        nav_audience: 'Audience',
        nav_name: 'Name',
        nav_logo: 'Logo',
        nav_icon: 'Icon',
        nav_typo: 'Typography',
        nav_colors: 'Colors',
        nav_expert: 'Expert',
        nav_mockups: 'Application',
        nav_dont: 'Prohibited',
        nav_digital: 'Domain',
        nav_contacts: 'Contacts',
        s00_tag: '05 — Target Audience',
        s00_title: 'Who I Help',
        s00_desc: 'The brand is created for three clearly defined audiences — each with its own task and entry point.',
        aud1_num: '01', aud2_num: '02', aud3_num: '03',
        aud_goal: 'Request',
        aud1_title: 'Crisis and Search',
        aud1_text: 'People going through difficult life periods, crises, loss of meaning or professional burnout. They are looking for support and a way out of the impasse.',
        aud1_goal: 'Finding support · Overcoming crisis',
        aud2_title: 'Awareness and Transformation',
        aud2_text: 'Those who are actively engaged in self-discovery, want to understand their true desires and motives. They need deep transpersonal practices and numerology.',
        aud2_goal: 'Self-discovery · Spiritual growth',
        aud3_title: 'Fatigue and Burnout',
        aud3_text: 'People tired of the constant race, stress and pressure. They want to pause, restore inner resources and return to themselves at retreats.',
        aud3_goal: 'Resource recovery · Rest',
        s09_tag: '08 — Digital presence',
        s09_title: 'Recommended domain',
        s09_desc: 'A single brand address on the Internet. Use it in all materials — online and offline.',
        s09_rec: 'Recommended for registration',
        s09_avail: 'RU domain · Short and memorable address',
        s09_r1_tag: '✓ Website and email',
        s09_r1_text: 'Host the main site on <strong>ontat.ru</strong>. Use email in the format <strong>tatyana@ontat.ru</strong> — looks professional and builds trust.',
        s09_r2_tag: '✓ Social networks',
        s09_r2_text: 'Specify the domain <strong>ontat.ru</strong> in the description of Instagram, Telegram, WhatsApp profiles. A single entry point for the audience from any channel.',
        s09_r3_tag: '✓ Printed materials',
        s09_r3_text: 'Business cards, flyers, certificates, banners — specify <strong>ontat.ru</strong> everywhere. Without unnecessary characters: no http://, www. or slash at the end.',
        s09_r4_tag: '✓ Uniformity',
        s09_r4_text: 'One domain — one address in all channels. This forms brand awareness and simplifies navigation for clients. Do not use third-party services (Taplink, Linktree) as the main address.',
        s09_note: 'The ontat.ru domain is recommended to be registered as soon as possible — before the start of active brand promotion. This will insure against the situation when the desired address is occupied.'
      },
      tr: {
        cover_tag: 'Marka Kitabı · 2026',
        cover_title: 'Kurumsal Kimlik Kılavuzu',
        cover_year: 'Stokholm · İstanbul · 2026',
        mission_quote: '<span style="color: #9830D5;">Farkındalık</span>, <span style="color: #9830D5;">dönüşüm</span> ve gerçek doğanıza dönüş yolunda güvenilir bir köprü olmak.',
        mission_sub: 'Misyonum',
        strategy_label: 'Stratejim',
        strategy_text: 'Anlık sorunları çözmekle yetinmiyorum. Kişi yolda olduğu sürece, <span style="color: #9830D5;">sonuca kadar yanındayım</span>.',
        s01_tag: '01 — İsim',
        s01_title: 'Ne anlama geliyor',
        fin_origin: 'Finance',
        fin_desc: 'Finans',
        guide_origin: 'Guide',
        guide_desc: 'Rehber',
        expert_origin: 'Expertus',
        expert_desc: 'Uzman',
        mc1_title: 'İsim Seçimi',
        mc1_text: 'Bilinçli bir seçim',
        mc2_title: 'Konumlandırma',
        mc2_text: 'Kişisel navigatör',
        mc3_title: 'Akılda Kalıcılık',
        mc3_text: 'Uluslararası, kısa, akılda kalıcı',
        mc4_title: 'Ölçeklenebilirlik',
        mc4_text: 'Coğrafyaya bağlı değil',
        s02_tag: '01 — Logo',
        s02_title: 'Logo ve sembolizmi',
        le1_title: 'Tatyana',
        le1_text: 'uzmanın adıdır',
        le2_title: 'Ontyurkler',
        le2_text: 'uzmanın soyadıdır',
        logo_versions: 'Logo versiyonları',
        lv1_label: '01 — Ana',
        lv1_text: 'Açık ve nötr arka planlarda. Belgeler, web sitesi, sunumlar, sosyal ağlar.',
        lv2_label: '02 — Koyu arka planda',
        lv2_text: 'Siyah üzerine logo. Afişler, koyu kapaklar, promosyon malzemeleri.',
        lv3_label: '03 — Tek renkli',
        lv3_text: 'Siyah tek renkli. Açık renkli medya üzerine baskı, damgalar, nakış, gravür.',
        s021_tag: '02 — İkon',
        s021_title: 'Grafik sembol',
        icon_desc: 'İkon, markanın bağımsız bir grafik sembolüdür. Tam adın uygun olmadığı yerlerde kullanılır.',
        icon_d1_title: 'Dijital medya',
        icon_d1_text: 'Web sitesi Favicon\'u, Instagram / Telegram / WhatsApp avatarı, mobil uygulama simgesi.',
        icon_d2_title: 'Baskı ve paketleme',
        icon_d2_text: 'Damga, çıkartma, kapakta kabartma, belgelerde filigran.',
        icon_d3_title: 'Dekoratif öğe',
        icon_d3_text: 'Sunumların arka planındaki desen, sayfanın köşe dekorasyonu.',
        icon_d4_title: 'Gereksinimler',
        icon_d4_text: 'Minimum boyut — 32×32 px. Deforme etmeyin, yeniden boyamayın.',
        dl_tag: 'Kaynak dosyalar',
        dl_title: 'PSD formatında logo (Adobe Photoshop)',
        dl_desc: 'Vektör katmanları, logonun tüm sürümleri, düzenlenebilir kaynak',
        dl_btn: 'PSD\'yi İndir',
        s04_tag: '02 — Tipografi',
        s04_title: 'Kurumsal yazı tipi',
        font_sub: 'Ana yazı tipi (Google Fonts · Ücretsiz · Kiril · Latin · Türkçe)',
        font_sub_compacta: 'Tatyana ismi. Logoda kullanılır.',
        font_sub_bella: 'Ontyurkler soyadı. Logoda kullanılır.',
        fw1: 'Alt başlıklar, destekleyici metin',
        fw2: 'Gövde metni, açıklamalar',
        fw3: 'Aksanlar, alt yazılar',
        fw4: 'Başlıklar, logo',
        typo_rules_title: 'Kullanım kuralları',
        tr1_title: '✓ Ana yazı tipi — Montserrat',
        tr1_text: 'Metinlerde okunamadığı için web sitesinde, kitapçıklarda ve marka kitabında sadece Montserrat kullanılmaktadır.',
        tr2_title: '✓ Kiril, Latin, Türkçe',
        tr2_text: 'Montserrat gerekli tüm komut dosyalarını destekler. Belirli Türkçe harfler doğru görüntülenir.',
        tr3_title: '✗ Başka yazı tipleri kullanmayın',
        tr3_text: 'Markanın resmi materyallerinde Times New Roman, Arial, Comic Sans ve diğer yazı tiplerinin kullanılması yasaktır.',
        tr4_title: '✗ Bozmayın',
        tr4_text: 'Metni manuel olarak uzatmayın, sıkıştırmayın veya eğmeyin. Yalnızca yerleşik Montserrat stillerini kullanın.',
        s03_tag: '03 — Renkler',
        s03_title: 'Kurumsal palet',
        c1_role: 'Ana',
        c2_role: 'Aksan / Metin',
        c3_role: 'Arka plan',
        c4_role: 'Geçiş gradyanı',
        cm1_title: 'Mor — farkındalık ve derinlik',
        cm1_text: 'Derin mor dönüşümü, maneviyatı ve yeni bir seviyeye ulaşmayı sembolize eder.',
        cm2_title: 'Siyah — ciddiyet ve profesyonellik',
        cm2_text: 'Siyah güçlü bir kontrast yaratır, markaya birinci sınıf bir his, zarafet ve istikrar verir.',
        cm3_title: 'Gradyan — dinamikler ve geçiş',
        cm3_text: 'Zengin mordan derin siyaha yumuşak bir geçiş, dönüşüm sürecini ve enerji akışını sembolize eder.',
        cm4_title: 'Beyaz — saflık ve özgürlük',
        cm4_text: 'Beyaz, nefes alma alanı görevi görür. Hafiflik verir, açıklığı ve yeni bir başlangıç için hazır olmayı vurgular.',
        s06_tag: '04 — Uzman',
        s06_title: 'Markanın yüzü',
        expert_name: 'Ontyurkler<br/>Tatyana',
        expert_role: 'Transpersonel psikolog · Nümerolog · Geri çekilme programlarının yazarı',
        expert_bio_1: 'Çalışmalarımda, insanların doğalarını derinden anlamalarına, devam eden olayların anlamını görmelerine ve değişim zamanlarında içsel destek bulmalarına yardımcı oluyorum. Yaklaşımım psikoloji, transpersonel kendini keşfetme yöntemleri, numeroloji ve farkındalık uygulamalarını birleştiriyor.',
        expert_bio_2: 'Bireysel çalışmalara ek olarak, katılımcıların içsel kaynaklarını geri yükleyebilecekleri ve gerçek benlikleriyle tanışabilecekleri inziva programları oluşturuyorum. Benim için bir insanla çalışmak, onlara farkındalık yolunda eşlik etmek ve gerçek doğalarını ortaya çıkarmaktır.',
        s07_tag: '06 — Uygulama',
        s07_title: 'Gerçek hayatta logo',
        moc1: 'Kazınmış not defteri',
        moc2: 'Kartvizit',
        moc3: 'Neon tabela',
        moc4: 'Ürün · Tişört',
        moc5: 'Markalı kupa',
        s08_tag: '07 — Yasaklanmış kullanımlar',
        s08_title: 'Logo nasıl kullanılmaz',
        s08_desc: 'Logo markanın yüzüdür. Herhangi bir bozulma, tanınmayı ve profesyonel bir imajı yok eder.',
        d1_title: '✗ Uzatmak',
        d1_text: 'Logonun oranlarını değiştirmek yasaktır.',
        d2_title: '✗ Yeniden Boyamak',
        d2_text: 'Logonun kurumsal renklerini değiştirmek yasaktır.',
        d3_title: '✗ Eğmek',
        d3_text: 'Logo her zaman kesinlikle yatay olarak yerleştirilir.',
        d4_title: '✗ Renkli arka plan',
        d4_text: 'Logoyu parlak veya çok zıt arka planlara yerleştirmek yasaktır.',
        d5_title: '✗ Gölgeler ekleyin',
        d5_text: 'Logoya gölgeler, parlamalar ve herhangi bir efekt eklemek yasaktır.',
        d6_overlay: 'DİĞER METİN',
        d6_title: '✗ Öğeler ekleyin',
        d6_text: 'Logonun üstüne metin veya çerçeve yerleştirmek yasaktır.',
        ct_phone: 'Telefon',
        ct_address: 'Adres',
        ct_city: 'Aktobe',
        page_indicator: 'Stokholm · İstanbul · 2026',
        nav_audience: 'Kitle',
        nav_name: 'İsim',
        nav_logo: 'Logo',
        nav_icon: 'İkon',
        nav_typo: 'Tipografi',
        nav_colors: 'Renkler',
        nav_expert: 'Uzman',
        nav_mockups: 'Uygulama',
        nav_dont: 'Yasaklı',
        nav_digital: 'Alan Adı',
        nav_contacts: 'İletişim',
        s00_tag: '05 — Hedef Kitle',
        s00_title: 'Kime Yardım Ediyorum',
        s00_desc: 'Marka, her biri kendi görevine ve giriş noktasına sahip, açıkça tanımlanmış üç kitle için oluşturulmuştur.',
        aud1_num: '01', aud2_num: '02', aud3_num: '03',
        aud_goal: 'İstek',
        aud1_title: 'Kriz ve Arayış',
        aud1_text: 'Zorlu yaşam dönemlerinden, krizlerden, anlam kaybından veya mesleki tükenmişlikten geçen insanlar. Destek ve çıkmazdan bir çıkış yolu arıyorlar.',
        aud1_goal: 'Destek bulmak · Krizi aşmak',
        aud2_title: 'Farkındalık ve Dönüşüm',
        aud2_text: 'Kendini keşfetmeye aktif olarak katılanlar, gerçek arzularını ve güdülerini anlamak isterler. Derin transpersonel uygulamalara ihtiyaçları var.',
        aud2_goal: 'Kendini keşfetme · Ruhsal gelişim',
        aud3_title: 'Yorgunluk ve Tükenmişlik',
        aud3_text: 'Sürekli yarıştan, stresten ve baskıdan bıkmış insanlar. Duraklamak, iç kaynakları geri yüklemek ve inzivalarda kendilerine dönmek istiyorlar.',
        aud3_goal: 'Kaynak kurtarma · Dinlenme',
        s09_tag: '08 — Dijital Varlık',
        s09_title: 'Önerilen Alan Adı',
        s09_desc: 'İnternette tek bir marka adresi. Tüm materyallerde kullanın — çevrimiçi ve çevrimdışı.',
        s09_rec: 'Kayıt için önerilir',
        s09_avail: 'RU alan adı · Kısa ve akılda kalıcı adres',
        s09_r1_tag: '✓ Web sitesi ve E-posta',
        s09_r1_text: 'Ana siteyi <strong>ontat.ru</strong> üzerinde barındırın. <strong>tatyana@ontat.ru</strong> formatında e-posta kullanın — profesyonel görünür ve güven oluşturur.',
        s09_r2_tag: '✓ Sosyal ağlar',
        s09_r2_text: 'Instagram, Telegram, WhatsApp profillerinin açıklamasında <strong>ontat.ru</strong> alan adını belirtin.',
        s09_r3_tag: '✓ Basılı materyaller',
        s09_r3_text: 'Kartvizitler, el ilanları, sertifikalar, afişler — her yerde <strong>ontat.ru</strong> adresini belirtin.',
        s09_r4_tag: '✓ Bütünlük',
        s09_r4_text: 'Tüm kanallarda tek alan adı. Bu, marka bilinirliği oluşturur.',
        s09_note: 'ontat.ru alan adının mümkün olan en kısa sürede — aktif marka tanıtımından önce kaydedilmesi önerilir.'
      }
    };

        function setLang(lang) {
      const dict = T[lang];
      document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (dict[key] !== undefined) el.innerHTML = dict[key];
      });
      // Desktop buttons
      document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.textContent === lang.toUpperCase());
      });
      // Mobile buttons
      const mbRu = document.getElementById('mob-btn-ru');
      const mbEn = document.getElementById('mob-btn-en');
      const mbTr = document.getElementById('mob-btn-tr');
      if (mbRu) mbRu.classList.toggle('active', lang === 'ru');
      if (mbEn) mbEn.classList.toggle('active', lang === 'en');
      if (mbTr) mbTr.classList.toggle('active', lang === 'tr');

      document.documentElement.lang = lang;
      localStorage.setItem('fg_lang', lang);
      // Close mobile menu on language switch
      document.getElementById('mob-nav-btn')?.classList.remove('open');
      document.getElementById('mob-nav-menu')?.classList.remove('open');
    }

    // Init
    const saved = localStorage.getItem('fg_lang') || 'ru';
    setLang(saved);
